/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Buoy-draco.glb
*/

import React, { useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import Axios from 'axios'

export function Buoy(props) {
  const { nodes, materials } = useGLTF('/Buoy-draco.glb')
  const [data, setData] = useState(null)
  const [selected] = useState(false)
  // const [data, ]
  // let modelData = {}

  useEffect(() => {
    try {
      console.log('mount')
      const fetchData = async () => {
        console.log('fetch data every 1min')
        const response = await Axios.get(
          `${process.env.REACT_APP_API}/data/bus/`,
        )
        setData(response.data.NextBus)
        //setData(response.data)
        console.log(response.data.NextBus)
        // console.log(typeof response.data)
      }
      fetchData()
      const intervalId = setInterval(fetchData, 1000 * 60)
      return () => {
        console.log('unmount')
        clearInterval(intervalId)
      }
    } catch (error) {
      console.log('error', error)
    }
  }, [])

  return (
    <>
      <group
        {...props}
        dispose={null}
        onPointerDown={(e) => {
          e.stopPropagation()
          console.log('click', !selected, data)
          props.data(data)
          props.clickMesh(!selected)
        }}
      >
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Circle03.geometry}
            material={materials.orange_glass}
            position={[0, 0, 1.38]}
          />
          <mesh
            geometry={nodes.Line02.geometry}
            material={materials.gold}
            position={[0, 0, 0.7]}
          />
          <mesh
            geometry={nodes.Object01.geometry}
            material={materials.aluminium_orange}
            position={[0, 0, 1.31]}
          />
          <mesh
            geometry={nodes.Object02.geometry}
            material={materials.aluminium_orange}
            position={[0, 0, 0.92]}
          />
          <mesh
            geometry={nodes.Rectangle01.geometry}
            material={materials.gold}
            position={[0, 0, 0.75]}
          />
          <mesh
            geometry={nodes.Line03.geometry}
            material={materials.aluminium_orange}
            position={[0, 0, 0.31]}
          />
          <mesh
            geometry={nodes.Circle02.geometry}
            material={materials.aluminium_orange}
            position={[0, 0, 1.44]}
          />
          <mesh
            geometry={nodes.Object03.geometry}
            material={materials.aluminium_orange}
            position={[0, 0, 1.02]}
          />
          <mesh
            geometry={nodes.Rectangle02.geometry}
            material={materials.aluminium_orange}
            position={[0, 0, 0.72]}
          />
        </group>
      </group>
    </>
  )
}

useGLTF.preload('/Buoy-draco.glb')
