/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Buoy-draco.glb
*/

import React, { useState, useEffect } from 'react'
import { Buoy } from './Buoy-draco'
import { RescueBoat } from './Rescue-boat-draco'
import { Html } from '@react-three/drei'
import * as THREE from 'three'



export const Models = (props) => {
  // const [htmlContent, setHtmlContent] = useState([])
  const handleSelectedData = (value) => {
    // setHtmlContent([...Object.entries(value)])
    props.selectedContent(value)
  }
  const handleClickMeshA = (value) => {
    props.clickMesh(value)
  }
  return (
    <React.Fragment>
      <Buoy
        scale={[5, 5, 5]}
        position={[0, -1, -15]}
        data={handleSelectedData}
        clickMesh={handleClickMeshA}
      />

      <RescueBoat
        scale={[50, 50, 50]}
        position={[5, -0.5, 0]}
        data={handleSelectedData}
        clickMesh={handleClickMeshA}
      />
    </React.Fragment>
  )
}
