/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Buoy-draco.glb
*/

import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'


const Buoy = (props) => {
  const { nodes, materials } = useGLTF('Buoy-draco.glb')
  const [selected] = useState(false)
  //props is a three.object3d
  return (
    <group
      {...props}
      dispose={null}
      onPointerDown={(e) => {
        e.stopPropagation()
        console.log('click', props.clickMesh)
        props.clickMesh(!selected)
        // setSelected(e.object.material.name)
        // state.current = e.object.material.name
      }}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          onClick={console.log('click')}
          geometry={nodes.Circle03.geometry}
          material={materials.orange_glass}
          position={[0, 0, 1.38]}
        />
        <mesh
          geometry={nodes.Line02.geometry}
          material={materials.gold}
          position={[0, 0, 0.7]}
        />
        <mesh
          geometry={nodes.Object01.geometry}
          material={materials.aluminium_orange}
          position={[0, 0, 1.31]}
        />
        <mesh
          geometry={nodes.Object02.geometry}
          material={materials.aluminium_orange}
          position={[0, 0, 0.92]}
        />
        <mesh
          geometry={nodes.Rectangle01.geometry}
          material={materials.gold}
          position={[0, 0, 0.75]}
        />
        <mesh
          geometry={nodes.Line03.geometry}
          material={materials.aluminium_orange}
          position={[0, 0, 0.31]}
        />
        <mesh
          geometry={nodes.Circle02.geometry}
          material={materials.aluminium_orange}
          position={[0, 0, 1.44]}
        />
        <mesh
          geometry={nodes.Object03.geometry}
          material={materials.aluminium_orange}
          position={[0, 0, 1.02]}
        />
        <mesh
          onClick={console.log('click')}
          geometry={nodes.Rectangle02.geometry}
          material={materials.aluminium_orange}
          position={[0, 0, 0.72]}
        />
      </group>
    </group>
  )
}
// useGLTF.preload('uoy-draco.glb')
export const Models = (props) => {
  const handleClickMesh = (value) => {
    props.clickMesh(value)
  }
  
  return (
    <React.Fragment>
      <Buoy clickMesh={handleClickMesh} />
      
    </React.Fragment>
  )
}

