/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 rescue-boat-draco.glb
*/

import React, { useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";

export function RescueBoat(props) {
  const { nodes, materials } = useGLTF("/rescue-boat-draco.glb");
  const [selected] = useState(false);
  const [data, setData] = useState("Rescue Boat Data")

  // useEffect(() => {
  //   try {
  //     props.data(data)
  //     props.clickMesh(!selected)
  //   } catch (error) {
  //     console.log('error', error)
  //   }
  // }, [data])


  return (
    <group
      {...props}
      dispose={null}
      // onPointerDown={(e) => {
      //   e.stopPropagation();
      //   console.log("click", !selected, data);
      //   props.data(data);
      //   props.clickMesh(!selected);
      // }}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rescue_BoatTOOLS.geometry}
        material={materials["Rescue_Boat:Assault_Boat_MAT"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rescue_BoatBOAT.geometry}
        material={materials["Rescue_Boat:Assault_Boat_MAT"]}
      />
    </group>
  );
}

useGLTF.preload("/rescue-boat-draco.glb");
