/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rescue_BoatTOOLS.geometry} material={materials['Rescue_Boat:Assault_Boat_MAT']} />
      <mesh geometry={nodes.Rescue_BoatBOAT.geometry} material={materials['Rescue_Boat:Assault_Boat_MAT']} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
